name: MD_Survivalplugin
version: 0.1.1
main: me.mdrunaway.survivalplugin.survivalplugin
description: Eine kleine Erweiterungen fuer den Survival Multiplayer
author: [MDRunaway]
commands:
  Test:
    description: Zum Testen ob das Plugin funktioniert
    usage: /<command>
  Farben:
    description: Zeigt die Farbcodes an
    usage: /<command>
  Suizid:
    description: Begehe Selbstmord!
    usage: /<command>